version: '2'
services:
    socialauction-app:
        image: socialauction
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://socialauction-postgresql:5432/socialAuction
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    socialauction-postgresql:
        extends:
            file: postgresql.yml
            service: socialauction-postgresql
