version: '2'
services:
    socialauction-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/socialAuction/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=socialAuction
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
